### ISSUE TITLE
We need some down-side to being hit

### ISSUE THREAD

**Issue by zephyyrr** [Victorystick/shimu-hd#22]
In the original game, being hit was an instant death.
In this, I want to improve it with a HP bar and invincibility frames on-hit.

Currently, Shimu is permanently invincible due to no collision-detection on enemies.

**Comment by Victorystick** [comment]
I'd like to structure the code in such a way that we are runtime can choose the collision behavior we want. That way it'd be easier to playtest different playstyles.

We could have a game mode (`LegacyLogic`?) so that people can experience the original, as well as a new and improved version of the game.

**Comment by zephyyrr** [comment]
A LegacyLogic sounds like a good idea. 
So should Logic contain a dictionary of some kind from Class to Class with collision behaviour?
And then once a collision is detected (CollisionSystem class?) it looks it up in the Logic implementation on what to do, matching on Classes.

This would needs to take inheritance into account as well, since we might not want to redefine it for every Bullet-Enemy combination. And some Bullets might want to do different things and some Enemies might react differently to different bullets.

Keeping it in each Entity is sort of bad anyway since what we are talking about is really the behaviour of two entities, not one which is what we model today and then it just mutates the other one without it getting a say in it.

**Comment by Victorystick** [comment]
We'll see how best to handle that. But I agree that we must do better than we've done so far.

As to the `LegacyLogic`, I think I may want to dive into the old Java code to get as close to the behavior of the original as possible.

Creating some `EntityIntelligence` would also be nice; like homing logic that can be reused for both enemies and bullets.

**Comment by zephyyrr** [comment]
Lets continue collision stuff in #28

**Comment by Victorystick** [comment]
To implement this according to the original rules, we just have to kill the player character on contact with anything hostile.

**Comment by zephyyrr** [comment]
Fixed in #42
